/** @type {import('tailwindcss').Config} */
import tailwindForms from '@tailwindcss/forms';
import tailwindTypography from '@tailwindcss/typography';
import tailwindAspectRatio from '@tailwindcss/aspect-ratio';

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          '50': 'rgb(var(--color-primary-50) / <alpha-value>)',
          '100': 'rgb(var(--color-primary-100) / <alpha-value>)',
          '200': 'rgb(var(--color-primary-200) / <alpha-value>)',
          '300': 'rgb(var(--color-primary-300) / <alpha-value>)',
          '400': 'rgb(var(--color-primary-400) / <alpha-value>)',
          '500': 'rgb(var(--color-primary-500) / <alpha-value>)',
          '600': 'rgb(var(--color-primary-600) / <alpha-value>)',
          '700': 'rgb(var(--color-primary-700) / <alpha-value>)',
          '800': 'rgb(var(--color-primary-800) / <alpha-value>)',
          '900': 'rgb(var(--color-primary-900) / <alpha-value>)',
          '950': 'rgb(var(--color-primary-950) / <alpha-value>)',
        },
        secondary: {
          '50': 'rgb(var(--color-secondary-50) / <alpha-value>)',
          '100': 'rgb(var(--color-secondary-100) / <alpha-value>)',
          '200': 'rgb(var(--color-secondary-200) / <alpha-value>)',
          '300': 'rgb(var(--color-secondary-300) / <alpha-value>)',
          '400': 'rgb(var(--color-secondary-400) / <alpha-value>)',
          '500': 'rgb(var(--color-secondary-500) / <alpha-value>)',
          '600': 'rgb(var(--color-secondary-600) / <alpha-value>)',
          '700': 'rgb(var(--color-secondary-700) / <alpha-value>)',
          '800': 'rgb(var(--color-secondary-800) / <alpha-value>)',
          '900': 'rgb(var(--color-secondary-900) / <alpha-value>)',
          '950': 'rgb(var(--color-secondary-950) / <alpha-value>)',
        },
        neutral: {
          '50': 'rgb(var(--color-neutral-50) / <alpha-value>)',
          '100': 'rgb(var(--color-neutral-100) / <alpha-value>)',
          '200': 'rgb(var(--color-neutral-200) / <alpha-value>)',
          '300': 'rgb(var(--color-neutral-300) / <alpha-value>)',
          '400': 'rgb(var(--color-neutral-400) / <alpha-value>)',
          '500': 'rgb(var(--color-neutral-500) / <alpha-value>)',
          '600': 'rgb(var(--color-neutral-600) / <alpha-value>)',
          '700': 'rgb(var(--color-neutral-700) / <alpha-value>)',
          '800': 'rgb(var(--color-neutral-800) / <alpha-value>)',
          '900': 'rgb(var(--color-neutral-900) / <alpha-value>)',
          '950': 'rgb(var(--color-neutral-950) / <alpha-value>)',
        },
        success: {
          '50': 'rgb(var(--color-success-50) / <alpha-value>)',
          '100': 'rgb(var(--color-success-100) / <alpha-value>)',
          '200': 'rgb(var(--color-success-200) / <alpha-value>)',
          '300': 'rgb(var(--color-success-300) / <alpha-value>)',
          '400': 'rgb(var(--color-success-400) / <alpha-value>)',
          '500': 'rgb(var(--color-success-500) / <alpha-value>)',
          '600': 'rgb(var(--color-success-600) / <alpha-value>)',
          '700': 'rgb(var(--color-success-700) / <alpha-value>)',
          '800': 'rgb(var(--color-success-800) / <alpha-value>)',
          '900': 'rgb(var(--color-success-900) / <alpha-value>)',
          '950': 'rgb(var(--color-success-950) / <alpha-value>)',
        },
        warning: {
          '50': 'rgb(var(--color-warning-50) / <alpha-value>)',
          '100': 'rgb(var(--color-warning-100) / <alpha-value>)',
          '200': 'rgb(var(--color-warning-200) / <alpha-value>)',
          '300': 'rgb(var(--color-warning-300) / <alpha-value>)',
          '400': 'rgb(var(--color-warning-400) / <alpha-value>)',
          '500': 'rgb(var(--color-warning-500) / <alpha-value>)',
          '600': 'rgb(var(--color-warning-600) / <alpha-value>)',
          '700': 'rgb(var(--color-warning-700) / <alpha-value>)',
          '800': 'rgb(var(--color-warning-800) / <alpha-value>)',
          '900': 'rgb(var(--color-warning-900) / <alpha-value>)',
          '950': 'rgb(var(--color-warning-950) / <alpha-value>)',
        },
        error: {
          '50': 'rgb(var(--color-error-50) / <alpha-value>)',
          '100': 'rgb(var(--color-error-100) / <alpha-value>)',
          '200': 'rgb(var(--color-error-200) / <alpha-value>)',
          '300': 'rgb(var(--color-error-300) / <alpha-value>)',
          '400': 'rgb(var(--color-error-400) / <alpha-value>)',
          '500': 'rgb(var(--color-error-500) / <alpha-value>)',
          '600': 'rgb(var(--color-error-600) / <alpha-value>)',
          '700': 'rgb(var(--color-error-700) / <alpha-value>)',
          '800': 'rgb(var(--color-error-800) / <alpha-value>)',
          '900': 'rgb(var(--color-error-900) / <alpha-value>)',
          '950': 'rgb(var(--color-error-950) / <alpha-value>)',
        },
      },
      fontFamily: {
        sans: ['var(--font-family-sans)'],
        serif: ['var(--font-family-serif)'],
        mono: ['var(--font-family-mono)'],
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
        '6xl': 'var(--font-size-6xl)',
        '7xl': 'var(--font-size-7xl)',
        '8xl': 'var(--font-size-8xl)',
        '9xl': 'var(--font-size-9xl)',
      },
      fontWeight: {
        thin: 'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light: 'var(--font-weight-light)',
        normal: 'var(--font-weight-normal)',
        medium: 'var(--font-weight-medium)',
        semibold: 'var(--font-weight-semibold)',
        bold: 'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
        black: 'var(--font-weight-black)',
      },
      lineHeight: {
        none: 'var(--line-height-none)',
        tight: 'var(--line-height-tight)',
        snug: 'var(--line-height-snug)',
        normal: 'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose: 'var(--line-height-loose)',
      },
      letterSpacing: {
        tighter: 'var(--letter-spacing-tighter)',
        tight: 'var(--letter-spacing-tight)',
        normal: 'var(--letter-spacing-normal)',
        wide: 'var(--letter-spacing-wide)',
        wider: 'var(--letter-spacing-wider)',
        widest: 'var(--letter-spacing-widest)',
      },
      spacing: {
        px: 'var(--spacing-px)',
        '0': 'var(--spacing-0)',
        '0.5': 'var(--spacing-0-5)',
        '1': 'var(--spacing-1)',
        '1.5': 'var(--spacing-1-5)',
        '2': 'var(--spacing-2)',
        '2.5': 'var(--spacing-2-5)',
        '3': 'var(--spacing-3)',
        '3.5': 'var(--spacing-3-5)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '7': 'var(--spacing-7)',
        '8': 'var(--spacing-8)',
        '9': 'var(--spacing-9)',
        '10': 'var(--spacing-10)',
        '11': 'var(--spacing-11)',
        '12': 'var(--spacing-12)',
        '14': 'var(--spacing-14)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
        '28': 'var(--spacing-28)',
        '32': 'var(--spacing-32)',
        '36': 'var(--spacing-36)',
        '40': 'var(--spacing-40)',
        '44': 'var(--spacing-44)',
        '48': 'var(--spacing-48)',
        '52': 'var(--spacing-52)',
        '56': 'var(--spacing-56)',
        '60': 'var(--spacing-60)',
        '64': 'var(--spacing-64)',
        '72': 'var(--spacing-72)',
        '80': 'var(--spacing-80)',
        '96': 'var(--spacing-96)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'none',
      },
      zIndex: {
        '0': 'var(--z-0)',
        '10': 'var(--z-10)',
        '20': 'var(--z-20)',
        '30': 'var(--z-30)',
        '40': 'var(--z-40)',
        '50': 'var(--z-50)',
        auto: 'var(--z-auto)',
      },
      transitionProperty: {
        'all': 'var(--transition-all)',
        'colors': 'var(--transition-colors)',
        'opacity': 'var(--transition-opacity)',
        'shadow': 'var(--transition-shadow)',
        'transform': 'var(--transition-transform)',
      },
      // Additional custom theme settings
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in',
        'slide-in': 'slide-in 0.3s ease-out',
      },
    },
  },
  plugins: [
    tailwindForms,
    tailwindTypography,
    tailwindAspectRatio,
  ],
} 